name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    env: 
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: yarn install

      # Run Lint
      - name: Run ESLint
        run: yarn lint

      # Build project
      - name: Build project
        run: yarn build

      # Migrate Prisma
      - name: Migrate Prisma
        run: yarn prisma migrate deploy

      # Run Tests
      - name: Run Jest Tests
        run: yarn test

  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: ci  
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Deploy to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod --yes'
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.TEAM_ID }}
